### ISSUE TITLE
Newsday source is broken

### ISSUE THREAD

**Issue by ieure** [yourealwaysbe/forkyz#32] opened 2021-09-15 15:20 UTC
Weird issue here.

To reproduce:
 - Set Newsday and Universal as the only puzzle sources.
 - Tap +
 - Select any date
 - Tap DOWNLOAD
 - Observe that the Universal puzzle downloads, but Newsday does not

Newsday was definitely working on 2021-09-08, and broken a couple days later.  It's not specific to the day — if you try to download 9/8 or older puzzles today, it doesn't work, even though it worked at the time.

I'm using the latest Forkyz from F-Droid, which looks like version 10.

I thought maybe Newsday changed something on their end, but that source still works in Shortyz, which hasn't been updated since mid-2020.

I also thought it might be something on my new phone (Unihertz Titan Pocket), but I can reproduce the same issue on my old phone (Pixel 3a running CalyxOS).

So, not sure how this happens, but all signs point to something in Forkyz.

**Comment by matthewhague** [comment] 2021-09-15 15:30
Confirmed on my end -- i'll have a look when i can.

Thanks for the report!

**Comment by matthewhague** [comment] 2021-09-15 22:41
Fixed in the version12 branch, i think.

It looks like i changed the date format in the URL from YYMMDD to YYYYMMDD back in April. I guess that was for a reason, but it seems to need changing back now.

**Comment by yourealwaysbe** [comment] 2021-09-16 13:05
Until Version 12 is out, a workaround is to download the puzzles in a browser using the URL format below (where 210915 is 15 September 2021 in the format YYMMDD).

> https://brainsonly.com/servlets-newsday-crossword/newsdaycrossword?date=210915

Then you can save that to a file and open it with the import feature of Forkyz.

**Closed as completed** 2021-09-18 10:25 UTC
