### ISSUE TITLE
Wierd bug/glitch 

### ISSUE THREAD

**Issue by dtoxic47** [yourealwaysbe/forkyz#52] opened 2022-07-17 17:34 UTC
Best i can explain this...opening a puzzle (new after download) and entering a letter in the box the whole puzzle gets brighter,like when you turn up the brightness on your phone,like if you turn on contrast up on a pc monitor and get a grayish washed up color (i checked my brightnes levels on my phone even turned off automatic brightness and thats not it) i did not manage to take a screenshot,this is totally random as far as i can tell,i use the dark theme.

Exiting the puzzel and reenter it the problem is no longer there.

**Comment by yourealwaysbe** [comment] 2022-07-17 17:49
Is it every time you enter a letter? Are you using the native keyboard?

My best guess is that the playboard is receiving focus, and the system is showing it has focus by putting a transparent grey box over it.

I can trigger similar behaviour on the browse menu if using a hardware keyboard and tabbing my way through the different UI elements. Occasionally i've seen it happen without a hardware keyboard, but don't know what causes it.

Does it go away if you tap on some other part of the screen. E.g. the clue line at the top (bringing up a clue list you can also try tapping on), or the menu? It might not help since focus tends to get returned to the playboard when anything is changed.

**Comment by dtoxic47** [comment] 2022-07-17 18:57
No it's totally random and i cant reproduce it at will...it happens when it happens i cant find a pattern to it,i use forkyz keyboard,it goes away after i go back to the puzzle list and then re enter the puzzle then everything is ok and i doesn't come back for maybe 2-3 or more days, but then again i dont enter the puzzle every day so like i said i tried to find a pattern to reproduce it but cant find anything

**Comment by yourealwaysbe** [comment] 2022-07-17 19:12
No problem. I'm fairly sure it'll be the focus thing. I think i need to override the default "is selected" representation to something more reasonable. I'll have a play around.

Thanks for the report!

**Comment by dtoxic47** [comment] 2022-07-17 19:17
Thank you for looking into it, have fun

**Comment by yourealwaysbe** [comment] 2022-07-20 06:49
I've added an experimental fix that'll go into the next version (25). Let me know if it helps when it's released.

My theory is that the highlight happens because the device is not in touch mode (i.e. it thinks you are using e.g. a dpad to pick UI elements before interacting, rather than using a touch screen). I think what's causing it to leave touch mode are the key events from the Forkyz keyboard. There are two system flags i wasn't setting that should tell the device that the key events are not hardware and shouldn't change touch mode.

**Comment by dtoxic47** [comment] 2022-07-20 08:16
Awesome,i will let you know if it occurs again

**Comment by dtoxic47** [comment] 2022-07-27 17:03
Here it is i remembered to take a screenshot this time,this one happened when the first letter was entered in Sheffer Crossword (don't know if that has to do with anything),and again after i exited the crossword i could not reproduce it again, i even deleted and re downloaded the crosswords and could not get it to act up again,hope it helps

btw. this is still version 24

![Screenshot_20220727-183051_Forkyz](https://user-images.githubusercontent.com/7866071/181306042-f2ff2e7f-e328-40a3-83f4-40612d42842d.jpg)

**Comment by yourealwaysbe** [comment] 2022-07-27 18:35
Thanks -- that looks how i expected. I can reproduce it by connecting up a hardware keyboard (actually, using [scrcpy](https://github.com/Genymobile/scrcpy) to control the phone from my laptop keyboard) and tabbing around. It's intended behaviour with a hardware keyboard (when you're picking UI elements with tab), even if it's not the prettiest it could look.

https://user-images.githubusercontent.com/372397/181346404-7b28827a-f13a-4806-8cc4-af2959e198fd.mp4

It looks like Version 25 is in FDroid now. Hopefully that stops it going into highlight mode (which i can't find a way out of) when you're using the touchscreen. The actual puzzle itself doesn't matter.

**Comment by dtoxic47** [comment] 2022-07-27 19:37
Cool, i will let you know if it happens again on v25! thx for taking the time to look into this

**Comment by ChainChomsky** [comment] 2022-08-15 21:35
i'd like to confirm that i had been having this problem multiple times on every puzzle (and sometimes seemingly stacking on top of each other?) and the most recent f-droid update has completely solved the problem.

**Comment by yourealwaysbe** [comment] 2022-08-16 20:53
Awesome, thanks. I'll close this now (hopefully we won't have to reopen it).

**Closed as completed by yourealwaysbe** 2022-08-16 20:53 UTC
